Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,6 +13,11 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        
+      - name: Build JAR
+        run: |
+          chmod +x ./gradlew
+          ./gradlew clean bootJar
 
       - name: Verify source files
         run: |
@@ -20,15 +25,21 @@ jobs:
             echo "Error: docker-compose.yml not found"
             exit 1
           fi
+          if [ ! -f ./build/libs/*.jar ]; then
+            echo "Error: JAR file not found"
+            exit 1
+          fi
 
-      - name: Copy Docker Compose file to server
+      - name: Copy files to server
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.SSH_HOST }}
           username: ec2-user
           key: ${{ secrets.SSH_KEY }}
           port: 22
-          source: ./docker-compose.yml
+          source: |
+            ./docker-compose.yml
+            ./build/libs/*.jar
           target: "/home/ec2-user/"
           debug: true
 
@@ -41,3 +52,11 @@ jobs:
           port: 22
           script: |
             ls -al /home/ec2-user/
+
+      - name: Restart application on EC2
+        uses: appleboy/ssh-action@v0.1.6
+        with:
+          script: |
+            cd /home/ec2-user/
+            docker-compose down --remove-orphans
+            docker-compose up -d
